version: '3.5'

services:
  dashboard:
    image: charypar/swarm-dashboard:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 4040:8080
    environment:
      PORT: 8080
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.backend=dashboard'
        #traefik.frontend.rule: Host:dashboard.${CLUSTER_DOMAIN}
        - 'traefik.frontend.rule=PathPrefixStrip:/dashboard;Host:${CLUSTER_DOMAIN}'   
        - 'traefik.port= 8080'
        - 'traefik.docker.network= traefik-net'
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - traefik-net

networks:
  admin-net:
    driver: overlay
  traefik-net:
    external: true
      
volumes:
  portainer: {}